# Site settings
title: Internet Research Laboratory, UCLA
#email: jdellaverson@cs.ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  Internet Research Laboratory at UCLA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://irl.cs.ucla.edu" # the base hostname & protocol for your site
#twitter_username: irl
#github_username:  jdellaverson19

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "blog/page:num"