# Site settings
title: IRL
email: jdellaverson@cs.ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  Here's a description of the IRL
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: irl
github_username:  jdellaverson19

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "blog/page:num"